ENV['DB_ADAPTER'] = 'mysql2'

ENV.delete('DATABASE_URL')
ENV.delete('DATABASE_REPLICA_URL')
ENV.delete('DATABASE_REPLICA1_URL')
ENV.delete('DATABASE_REPLICA2_URL')
ENV.delete('DATABASE_FAKE_REPLICA_URL')
